import type { Rule } from '../types.js';

export const patternRules: Rule[] = [
  {
    id: 'aws-access-key',
    description: 'Potential AWS access key ID',
    type: 'Possible AWS Access Key',
    severity: 'high',
    category: 'pattern',
    pattern: /\b(?:AKIA|ASIA|ABIA|ACCA)[A-Z0-9]{16}\b/g,
  },
  {
    id: 'github-token',
    description: 'Potential GitHub personal or fine-grained token',
    type: 'Possible GitHub Token',
    severity: 'critical',
    category: 'pattern',
    pattern: /\bgh[pousr]_[A-Za-z0-9_]{20,255}\b/g,
  },
  {
    id: 'gitlab-token',
    description: 'Potential GitLab personal, project, or runner token',
    type: 'Possible GitLab Token',
    severity: 'critical',
    category: 'pattern',
    pattern: /\bgl(?:pat|proj|rt)-[A-Za-z0-9_-]{20,}\b/g,
  },
  {
    id: 'npm-token',
    description: 'Potential npm access token',
    type: 'Possible npm Token',
    severity: 'critical',
    category: 'pattern',
    pattern: /\bnpm_[A-Za-z0-9]{36}\b/g,
  },
  {
    id: 'google-api-key',
    description: 'Potential Google API key',
    type: 'Possible Google API Key',
    severity: 'high',
    category: 'pattern',
    pattern: /\bAIza[0-9A-Za-z_-]{35}\b/g,
  },
  {
    id: 'stripe-key',
    description: 'Potential Stripe key',
    type: 'Possible Stripe Key',
    severity: 'critical',
    category: 'pattern',
    pattern: /\b(?:sk|rk)_(?:live|test)_[A-Za-z0-9]{16,}\b/g,
  },
  {
    id: 'slack-token',
    description: 'Potential Slack token',
    type: 'Possible Slack Token',
    severity: 'high',
    category: 'pattern',
    pattern: /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/g,
  },
  {
    id: 'jwt',
    description: 'Potential JSON Web Token',
    type: 'Possible JWT',
    severity: 'medium',
    category: 'pattern',
    pattern: /\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/g,
  },
  {
    id: 'private-key',
    description: 'Private key material',
    type: 'Possible Private Key',
    severity: 'critical',
    category: 'pattern',
    pattern: /-----BEGIN (?:[A-Z0-9 ]+ )?PRIVATE KEY-----/g,
  },
  {
    id: 'bearer-token',
    description: 'Potential bearer token',
    type: 'Possible Bearer Token',
    severity: 'high',
    category: 'pattern',
    pattern: /\bBearer\s+[A-Za-z0-9._~+/-]{20,}/g,
  },
  {
    id: 'database-connection-string',
    description: 'Potential database connection string',
    type: 'Possible Database Connection String',
    severity: 'critical',
    category: 'pattern',
    pattern: /\b(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis):\/\/[^\s"'`]{8,}/gi,
  },
  {
    id: 'openai-api-key',
    description: 'Potential OpenAI API key',
    type: 'Possible OpenAI API Key',
    severity: 'critical',
    category: 'pattern',
    pattern: /\b(?:sk-(?:proj|admin)-[A-Za-z0-9_-]{32,}|sk-[A-Za-z0-9]{40,})\b/g,
  },
  {
    id: 'anthropic-api-key',
    description: 'Potential Anthropic API key',
    type: 'Possible Anthropic API Key',
    severity: 'critical',
    category: 'pattern',
    pattern: /\bsk-ant-(?:api03-)?[A-Za-z0-9_-]{32,}\b/g,
  },
  {
    id: 'huggingface-token',
    description: 'Potential Hugging Face access token',
    type: 'Possible Hugging Face Token',
    severity: 'critical',
    category: 'pattern',
    pattern: /\bhf_[A-Za-z0-9]{34,}\b/g,
  },
  {
    id: 'sendgrid-api-key',
    description: 'Potential SendGrid API key',
    type: 'Possible SendGrid API Key',
    severity: 'critical',
    category: 'pattern',
    pattern: /\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b/g,
  },
  {
    id: 'resend-api-key',
    description: 'Potential Resend API key',
    type: 'Possible Resend API Key',
    severity: 'critical',
    category: 'pattern',
    pattern: /\bre_[A-Za-z0-9_]{30,}\b/g,
  },
  {
    id: 'twilio-account-sid',
    description: 'Potential Twilio Account SID',
    type: 'Possible Twilio Account SID',
    severity: 'high',
    category: 'pattern',
    pattern: /\bAC[a-f0-9]{32}\b/gi,
  },
];
